Define			DisplayModel			{ Pixels }
Pixels			Shape					{ 'pixels' }
Define			DisplayModel			{ Rectangle }
Rectangle		Shape					{ 'rectangle' }
Define				DisplayModel		{ Circle }
Circle				Shape				{ 'circle' }
Define				DisplayModel		{ Arrow2D }
Arrow2D				Shape				{ 'arrow2D' }
Define				DisplayModel		{ Triangle }
Triangle			Shape				{ 'triangle' }
Define				DisplayModel		{ CrossHairs }
CrossHairs			Shape				{ '/resources/shapes/CrossHairs.dae' }

Define              DisplayModel		{ Cube }
Cube                Shape               { '/resources/shapes/cube.dae' }
DisplayEntity       DefaultDisplayModel { Cube }

Define              DisplayModel		{ Sphere }
Sphere              Shape               { '/resources/shapes/Sphere.dae' }
