Define ObjectType {
	DemoEntity
}

DemoEntity  JavaClass { com.jaamsim.Examples.DemoEntity }  Palette { 'Examples' }  DefaultDisplayModel { Sphere }  IconFile { '<res>/images/SimEntity-24.png' }  DefaultSize { 0.5 0.5 0.5 m }
DemoEntity  DragAndDrop { FALSE }  #Remove this line if the DemoEntity and Examples palette are to be displayed in the Model Builder

DemoEntity  Description { 'Object that moves back and forth between two nodes. Intended to provide an example of how to program a new simulaton object.' }
