Define Palette { 'Simulation Controls' }

Define ObjectType {
                    GraphicSimulation
                    EntityTracer
                  }

GraphicSimulation       JavaClass { com.sandwell.JavaSimulation.Simulation     } Palette { 'Simulation Controls' } DragAndDrop { FALSE }
EntityTracer            JavaClass { com.jaamsim.basicsim.EntityTracer          } Palette { 'Simulation Controls' } DragAndDrop { FALSE }

